language: java

env:
  - DB=mysql

jdk:
  - openjdk

mysql:
  database: es
  username: root
  password :
  encoding: utf8

install:
  - mvn install -Dmaven.test.skip=true

before_script:
  - cd web
  - mvn db:create
  - mvn db:schema
  - mvn db:data
  - cd ..

script:
  - cd common
  - mvn test
  - cd ..
  - cd web
  - mvn test -Ptest



notifications:
  email:
    - zhangkaitao0503@gmail.com